########################################
# EMPLOYEES-SERVICE
########################################

##### EMPLOYEE GET

### @name getEmployees
GET /employee HTTP/1.1
Host: localhost:8100

### @name getEmployeeByEmployeeNumber
GET /employee/000010 HTTP/1.1
Host: localhost:8100

### @name getEmployeeByEmployeeNumberNegative
GET /employee/abc123 HTTP/1.1
Host: localhost:8100

##### EMPLOYEE SEARCH

### @name getEmployeeSearch
GET /employee/search?fName=EILEEN&lName=SMITH HTTP/1.1
Host: localhost:8100

### @name getEmployeeSearchNoResults
GET /employee/search?fName=HELLO&lName=WORLD HTTP/1.1
Host: localhost:8100

### @name getEmployeeSearchFirstName
GET /employee/search?fName=EILEEN HTTP/1.1
Host: localhost:8100

### @name getEmployeeSearchLastName
GET /employee/search?lName=SMITH HTTP/1.1
Host: localhost:8100

### @name getEmployeeSearchNullParams
GET /employee/search HTTP/1.1
Host: localhost:8100

##### EMPLOYEE WORK DEPARTMENT

### @name getEmployeeByEmployeeWorkDepartment
GET /employee/deparment/A00 HTTP/1.1
Host: localhost:8100

### @name getEmployeeByEmployeeWorkDepartmentNegative
GET /employee/deparment/abc HTTP/1.1
Host: localhost:8100