services:
  db2:
    image: ibmcom/db2
    container_name: db2
    hostname: db2server
    privileged: true
    ports:
      - "50000:50000"
    environment:
      LICENSE: 'accept'
      DB2INST1_PASSWORD: 'db2inst1'
      DBNAME: 'INVDB'
    volumes:
      - ./db2/database:/database
  app:
     build: .
     container_name: app